## Put comments here that give an overall description of what your
## functions do


##First Function: makeCacheMatrix
##Creates a special object matrix and its functions setMatrix, getMatrix, setInverse, getInverse
##with M the matrix which we want to cache the inverse
##with s the result of matrix M inversion, so it's the result we want to cache

makeCacheMatrix<-function(x = matrix()){
        
        s<-NULL 
        
        setMatrix <- function(M) {
                
                x <<- M               
                s <<- NULL
        }
        
        
        getMatrix <- function() x
        
        
        setInverse <- function(Inverse) {s <<- Inverse
        }
        
        getInverse <- function() s       
        
        list(setMatrix = setMatrix, getMatrix = getMatrix,
             setInverse = setInverse,
             getInverse = getInverse)
        
        
        
}



##Second Function: 
##Return 'i' the matrix that is the inverse of 'x'
##N.B.: 'x' should be a Matrix created thanks to special object generated by 'makeCacheMatrix' and its function 'setMatrix'

cacheSolve <- function(x, ...) {
        
        
        i <- x$getInverse()
        
        
        if(!is.null(i)) {
                
                message("Inverse available and cached, getting this cached data")
                
                return(i)
        }
        
        
        else 		{
                data <- x$getMatrix()
                
                i <- solve(data, ...)
                
                x$setInverse(i)
                
                return(i)}
        
}